# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = prompt(
      text: "Changelog: ",
      multi_line_end_keyword: "END")

    increment_build_number(xcodeproj: "VerbozeMobile.xcodeproj")

    xcclean

    build_app(
      scheme: "VerbozeMobile",
      include_bitcode: true)

    notification(
      subtitle: "Finished VerbozeMobile iOS beta build",
      sound: "purr",
      message: "Read to upload to TestFlight")

    upload_to_testflight

    download_dsyms

    sentry_upload_dsym(
      auth_token: "c461695a8ab445979566f1813fe54489c1026ea238c44ede91037ef6af3358c9",
      org_slug: "verboze",
      project_slug: "verboze-mobile")

    slack(
      message: "Successfully distributed a new iOS beta build",
      slack_url: "https://hooks.slack.com/services/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",
      channel: "#fastlane",
      success: true)
  end

  desc "Upload beta builds DSYM files to Sentry"
  lane :beta_do_sentry do
    download_dsyms

    sentry_upload_dsym(
      auth_token: "c461695a8ab445979566f1813fe54489c1026ea238c44ede91037ef6af3358c9",
      org_slug: "verboze",
      project_slug: "verboze-mobile")
  end
end
